"""add_subscription_and_invite_codes

Revision ID: 29672f48c359
Revises: 1ea01d592526
Create Date: 2026-01-23 19:25:16.698590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29672f48c359'
down_revision: Union[str, Sequence[str], None] = '1ea01d592526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grants_plan', sa.String(), nullable=False),
    sa.Column('is_beta_code', sa.Boolean(), nullable=False),
    sa.Column('beta_duration_days', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_codes_code'), 'invite_codes', ['code'], unique=True)
    op.create_index(op.f('ix_invite_codes_id'), 'invite_codes', ['id'], unique=False)
    # REMOVED: op.drop_index and op.drop_table for journey_templates (table should remain)
    
    # Add columns with nullable=True first, then set defaults and make them NOT NULL
    op.add_column('users', sa.Column('subscription_plan', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_beta_tester', sa.Boolean(), nullable=True))
    
    # Set default values for existing users
    op.execute("UPDATE users SET subscription_plan = 'free' WHERE subscription_plan IS NULL")
    op.execute("UPDATE users SET subscription_status = 'active' WHERE subscription_status IS NULL")
    op.execute("UPDATE users SET is_beta_tester = false WHERE is_beta_tester IS NULL")
    
    # Now make them NOT NULL
    op.alter_column('users', 'subscription_plan', nullable=False)
    op.alter_column('users', 'subscription_status', nullable=False)
    op.alter_column('users', 'is_beta_tester', nullable=False)
    
    # Add the rest of the columns (already nullable)
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('beta_expires_at', sa.DateTime(timezone=True), nullable=True))
    
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_users_stripe_subscription_id'), 'users', ['stripe_subscription_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_subscription_id'), table_name='users')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_column('users', 'beta_expires_at')
    op.drop_column('users', 'is_beta_tester')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'subscription_plan')
    # REMOVED: journey_templates recreation in downgrade (table should remain)
    op.drop_index(op.f('ix_invite_codes_id'), table_name='invite_codes')
    op.drop_index(op.f('ix_invite_codes_code'), table_name='invite_codes')
    op.drop_table('invite_codes')
    # ### end Alembic commands ###
