"""add_mileage_claims_table

Revision ID: 573b6efd43eb
Revises: 9feb0ffccb8a
Create Date: 2026-01-20 21:43:53.016356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573b6efd43eb'
down_revision: Union[str, Sequence[str], None] = '9feb0ffccb8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mileage_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_location', sa.Text(), nullable=False),
    sa.Column('end_location', sa.Text(), nullable=False),
    sa.Column('start_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('start_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('end_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('end_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('distance_miles', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vehicle_type', sa.Enum('CAR', 'MOTORCYCLE', 'BICYCLE', name='vehicletype'), nullable=False),
    sa.Column('is_round_trip', sa.Boolean(), nullable=False),
    sa.Column('hmrc_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('claim_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('business_purpose', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mileage_claims')
    # ### end Alembic commands ###
