"""add_hmrc_expense_categories

Revision ID: 677427a3df36
Revises: 644e419d84b5
Create Date: 2026-01-19 21:13:50.611986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '677427a3df36'
down_revision: Union[str, Sequence[str], None] = '644e419d84b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the enum type
    expense_category_enum = sa.Enum('OFFICE_COSTS', 'TRAVEL_COSTS', 'CLOTHING', 'STAFF_COSTS', 'STOCK_MATERIALS', 'FINANCIAL_COSTS', 'BUSINESS_PREMISES', 'ADVERTISING_MARKETING', 'TRAINING', 'OTHER', name='expensecategory')
    expense_category_enum.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receipts', 'category',
               existing_type=sa.VARCHAR(),
               type_=expense_category_enum,
               existing_nullable=True,
               postgresql_using='category::expensecategory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receipts', 'category',
               existing_type=sa.Enum('OFFICE_COSTS', 'TRAVEL_COSTS', 'CLOTHING', 'STAFF_COSTS', 'STOCK_MATERIALS', 'FINANCIAL_COSTS', 'BUSINESS_PREMISES', 'ADVERTISING_MARKETING', 'TRAINING', 'OTHER', name='expensecategory'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    
    # Drop the enum type
    sa.Enum(name='expensecategory').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
