"""add duplicate detection fields to receipts

Revision ID: 9b984a6823ef
Revises: 573b6efd43eb
Create Date: 2026-01-21 22:23:17.453139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b984a6823ef'
down_revision: Union[str, Sequence[str], None] = '573b6efd43eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('duplicate_suspect', sa.Integer(), nullable=True))
    op.add_column('receipts', sa.Column('duplicate_of_id', sa.Integer(), nullable=True))
    op.add_column('receipts', sa.Column('duplicate_dismissed', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'receipts', 'receipts', ['duplicate_of_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.drop_column('receipts', 'duplicate_dismissed')
    op.drop_column('receipts', 'duplicate_of_id')
    op.drop_column('receipts', 'duplicate_suspect')
    # ### end Alembic commands ###
