"""update_audit_logs_foreign_key

Revision ID: 9feb0ffccb8a
Revises: 79bc91a4db12
Create Date: 2026-01-20 14:42:20.921323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9feb0ffccb8a'
down_revision: Union[str, Sequence[str], None] = '79bc91a4db12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'receipt_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('audit_logs_receipt_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'receipts', ['receipt_id'], ['id'], ondelete='SET NULL')
    op.add_column('receipts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'deleted_at')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_receipt_id_fkey'), 'audit_logs', 'receipts', ['receipt_id'], ['id'], ondelete='CASCADE')
    op.alter_column('audit_logs', 'receipt_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
