"""add_stripe_subscription_fields

Revision ID: c8a88100c2ca
Revises: 584f6de0598c
Create Date: 2026-01-29 14:20:25.860903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8a88100c2ca'
down_revision: Union[str, Sequence[str], None] = '584f6de0598c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # REMOVED: op.drop_index and op.drop_table for journey_templates (table should remain)
    op.add_column('users', sa.Column('subscription_current_period_end', sa.DateTime(timezone=True), nullable=True))
    # Add subscription_cancel_at_period_end as nullable first, then set default, then make it NOT NULL
    op.add_column('users', sa.Column('subscription_cancel_at_period_end', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET subscription_cancel_at_period_end = false WHERE subscription_cancel_at_period_end IS NULL")
    op.alter_column('users', 'subscription_cancel_at_period_end', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_cancel_at_period_end')
    op.drop_column('users', 'subscription_current_period_end')
    # REMOVED: journey_templates recreation in downgrade (table should remain)
    # ### end Alembic commands ###
