"""add_stripe_subscription_fields

Revision ID: c8a88100c2ca
Revises: 584f6de0598c
Create Date: 2026-01-29 14:20:25.860903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8a88100c2ca'
down_revision: Union[str, Sequence[str], None] = '584f6de0598c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journey_templates_user_id'), table_name='journey_templates')
    op.drop_table('journey_templates')
    op.add_column('users', sa.Column('subscription_current_period_end', sa.DateTime(timezone=True), nullable=True))
    # Add subscription_cancel_at_period_end as nullable first, then set default, then make it NOT NULL
    op.add_column('users', sa.Column('subscription_cancel_at_period_end', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET subscription_cancel_at_period_end = false WHERE subscription_cancel_at_period_end IS NULL")
    op.alter_column('users', 'subscription_cancel_at_period_end', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_cancel_at_period_end')
    op.drop_column('users', 'subscription_current_period_end')
    op.create_table('journey_templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('start_location', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('end_location', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vehicle_type', postgresql.ENUM('CAR', 'MOTORCYCLE', 'BICYCLE', name='vehicletype'), autoincrement=False, nullable=False),
    sa.Column('business_purpose', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_round_trip', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('journey_templates_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('journey_templates_pkey'))
    )
    op.create_index(op.f('ix_journey_templates_user_id'), 'journey_templates', ['user_id'], unique=False)
    # ### end Alembic commands ###
